In [2]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [12]:
arr = np.array(my_list)

In [15]:
arr

array([1, 2, 3])

In [17]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
import numpy as np

my_mat = [[1,2,3],[4,5,6],[7,8,9]] #this is a simple list of list
values = np.array(my_mat) #the list is turned into an array and stored in values
print(values)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
import numpy as np

#the first input is 'start', second is 'stop', and third is 'step'
np.arange(0,11,2) # arange function is useful for generating arrays using numpy


array([ 0,  2,  4,  6,  8, 10])

In [16]:
import numpy as np

np.zeros(3) #arrays for only passing 'zeros', pass a single digit for one vector


array([0., 0., 0.])

In [20]:
import numpy as np

np.zeros((2,3)) #here you pass tuples you want. tuples are immutable.


array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#remember in python programming, the first input is 'ROWS', and the second are
#'COLUMNS'

In [24]:
import numpy as np

np.ones(4) #arrays for only passing 'ones'


array([1., 1., 1., 1.])

In [26]:
import numpy as np

np.ones((3,4)) #a two dimensional array of 'ones'

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
import numpy as np

np.linspace(0,5,10) #used to create evenly spaced numbers from between 
#starting point and ending value.


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [38]:
import numpy as np

np.eye(4) #this is an identity matrix,a two dimensional square matrix meaning
#the number of rows is same as the number of columns. was used in linear algebra


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
import numpy as np

np.random.rand(5) #randomly generates random samples from a uniform distribution,
#in this case, if you for example pass the input '5', then it will generate '5'
#random arrays from '0 - 1'. this is a one dimensional array


array([0.87216509, 0.63556552, 0.49653972, 0.30247121, 0.92759155])

In [44]:
import numpy as np

np.random.rand(4,5) #in this example instead of putting in a tuple, we simply
#just insert a starting value and an ending value for each dimension. Let's 
#say we want a ' 4 by 5'matrix. We insert ' 4' in the start and ' 5' in the 
#end, signafying that ' 4' is the number of ' rows' we want our matrix to have
#, while ' 5' is the number of columns we desire. Since we are utilizing the 
#' random.rand()' function of numpy, the values presented in the matrix's 
#output are randomized from ' 0 - 1'


array([[0.35065462, 0.02079658, 0.14018551, 0.44186167, 0.91836164],
       [0.4133968 , 0.80394376, 0.22262444, 0.81487504, 0.07003442],
       [0.29228849, 0.34646522, 0.74372024, 0.58221876, 0.93531426],
       [0.96427011, 0.75953573, 0.99209873, 0.79043682, 0.83269337]])

In [48]:
import numpy as np

np.random.randn(4) #using 'random.randn()' function of numpy, allows us to plot
#a standard normal distribution which falls under non-uniform distribution. This
#means that some values, numbers, or chances generated using this function
#have a higher chance of showing up than the others, compared to a uniform
#distribution where if you for example have a bag containing numbers 1-6 and 
#each group leader gets to randomly pick one, all papers have an equal chance 
#of being selected because there are also 6 group leaders.

array([ 0.86094261, -1.36663971, -0.02033868, -0.8415614 ])

In [50]:
import numpy as np

np.random.randn(4,4) #similar to when random.rand() function was performed,
#' random.randn()' can take a starting point and ending point value for each
#dimension to generate a two-dimesnional matrix.

array([[-0.62726062,  0.69065821, -1.43300728, -0.60769955],
       [-0.73320685,  0.34595129,  0.39803857,  0.81915096],
       [ 0.07370279,  0.67219489,  0.16063992, -0.54909184],
       [ 0.59029693, -1.23471973,  1.50778852,  0.56631726]])

In [58]:
import numpy as np

#the first input is 'lower bound', second is 'upper bound', inclusive for
#the low end and eclusive for the high end. For example, if '1' 
#is placed in your lower bound, and '100' on your upper bound,
#then numbers 1 and 100 also have a chance of being selected or are also 
#included.
np.random.randint(1,100)

#on the other hand a third argument would indicate that the programmer would
#like to generate that specific amount of numbers from the lower and upper
#bound range. In this case, '10' values will be displayed.
np.random.randint(1,100,10)

array([41, 76, 46, 69, 30, 82, 47, 28, 32, 52])

In [72]:
import numpy as np

arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 6,  3,  4, 31,  2, 46,  3, 27, 28,  5])

In [74]:
arr.reshape(5,5) #notice that by using the 'reshape()' function, the variable
#' arr' which stores another function, 'np.arange(25)' has been turned into a
#matrix of '5 by 5' as indicated in the first dimension, again known as 'row',
#and the second dimension, again known as 'column'.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
#IMPORTANT NOTE

#we have to note however, that the 'reshape()' function could work with the
#inputted dimensions of a '5 by 5' matrix, because the 'arr' variable stores
#a range of '25' numbers.

#if for example we wanted 'arr.reshape()' to have dimensions of '5 by 10',
#the program will have an error because the number of values would be too
#small to fill the matrix up. you can only fill up with only the existing
#number of elements you have. in the case where we called 'np.arange(25)', we
#get numbers '0-24'.

In [94]:
import numpy as np

ranarr = np.random.randint(0,50,10)

ranarr.max() #this function finds the max or highest value from the range

49

In [92]:
import numpy as np

ranarr = np.random.randint(0,50,10)

ranarr.min() #this function finds the minimum or lowerst value from the range

6

In [98]:
import numpy as np

ranarr = np.random.randint(0,50,10)

                           0   1   2   3   4   5   6   7   8   9
ranarr #output example [( 35, 18, 26, 49, 34, 48, 3, 30, 6, 6)]

#if ' ranarr.max()' displays the number '49' as the highest output then
ranarr.argmax() #this function finds the index position of it. In this case,
#'49' is indexed at number 3.

ranarr.argmin() #works the same way, but finds the index number of the
#lowest output. In this case, since '3' is the smallest value, it is 
#positioned in index number 6.

6

In [ ]:
arr.dtype() #this function will return the data type seen in your array.

In [7]:
#NEXT LESSONS---------------------------------------------------------------->

In [15]:
import numpy as np

arr = np.arange(0,11)
arr[8] #returning a desired number from an array is as simple as getting 
#the index in a list. simply put square brackets to indicate and then the
#index number which represents the value you want to return.


8

In [23]:
import numpy as np

arr = np.arange(0,11)
arr[1:5] #the starting index is '1' and the stopping index is '5'. Slicing 
#a range of numbers to get more than a single output in an array is just 
#the same as in a list.


array([1, 2, 3, 4])

In [27]:
import numpy as np

arr = np.arange(0,11)
arr[:6] #it is also possible to leave the starting index blank. this would
#signify that you want to output or display all the numbers BEFORE the ending
#index.


array([0, 1, 2, 3, 4, 5])

In [31]:
import numpy as np

arr = np.arange(0,11)
arr[5:] #this is similar to the previous example. however, numbers AFTER the
#indicated starting index, in this case ' 5' (still an index representation 
#not the actual '5' number) will be outputted.


array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#POSSIBLE QUESTIONS IN CONFUSING TO INDEX REPRESENTATION
------------------------------------------------------------
I am confused. If we are referring to an index representation, why is that
the array output displayed numbers ' 5-10' ?, instead of ' 4-10' since in this
case, the real number ' 4' is represented by the index number ' 5'?

    - This is because when you say for example, [5:], it means that you are
    grabbing the numbers WAY BEYOND index ' 5' itself. Simply, you start to
    display the numbers represented by the next index which is index ' 6'.
    It's as if you are saying that you are excluding index representation ' 5'
    and getting the numbers after it.


In [41]:
import numpy as np

arr = np.arange(0,11)
arr[0:5] = 100 #by equating it to ' 100', you set all real numbers represented
#by starting index ' 0' all the way to real numbers before stopping index ' 5',
#in this case you can imagine real numbers '0-4' to be represented by the
#number 100.
    
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
import numpy as np

arr = np.arange(0,11)

slice_of_arr = arr[0:6]

slice_of_arr


array([0, 1, 2, 3, 4, 5])

In [10]:
import numpy as np

arr = np.arange(0,11)

slice_of_arr = arr[0:6]

slice_of_arr[:] #no input in row or column dimensions mean that you want to
#broadcast the entire array, so everything will be displayed. 'Slice_of_arr' 
#stores 'arr[0:6]', so the display output would be elemnts from index number
#representations '0-6' meaning the starting point would be '0' but the stopping
#point '6' would not be included.


array([0, 1, 2, 3, 4, 5])

In [12]:
import numpy as np

arr = np.arange(0,11)

slice_of_arr = arr[0:6]

slice_of_arr[:] = 99 #this would set 'all' values to 99.

slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [14]:
import numpy as np

arr = np.arange(0,11)

slice_of_arr = arr[0:6]

slice_of_arr[:] = 99 

slice_of_arr #since 'all' values were set to 99, this would also change the
#values in the initial variable 'arr' and not just in variable 'slice_of_arr'

arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy() #This is a variable containing the '.copy()' function.
#what this does is that it can specifically indicate what you want to copy.
#in this case, the 'arr_copy' variable stores a complete copy of what is
#contained in initial variable 'arr'.

#so for example, if arr outputs '([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])'
#then 'arr_copy' variable would also output 
#'([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])'


In [22]:
#however if the variable is set this way, indexing the dimensions:
arr_copy[:] = 100
#then we can say that all variables now in 'arr_copy' has been changed to display
#'([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])'


In [20]:
#this means that variable:
arr
#when printed out retains the output of
#'([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])', as variable 'arr_copy' became
#independent of it.


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
#NEXT LESSONS---------------------------------------------------------------->

In [26]:
import numpy as np

arr_2d = np.array([[ 5, 10, 15],[ 20, 25, 30], [35, 40, 45]])

arr_2d #this outputs a two-dimensional matrix as it consists of 3 rows
# and 3 columns, more than a single line of previous array outputs.

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
import numpy as np

arr_2d = np.array([[ 5, 10, 15],[ 20, 25, 30], [35, 40, 45]])

arr_2d[1][1] #if you for example want to return the digit '5', you refer to it
#like this. the first '[1]' represents the second row. the second '[1]' 
#represents the second column. altogether the combination gets the item in the
#assigned position of it, which is '25'.

25

In [34]:
#YOU CAN DO DOUBLE BRACKETS OR A SINGLE BRACKET LIKE THE ONE BELOW------------->

In [36]:
import numpy as np

arr_2d = np.array([[ 5, 10, 15],[ 20, 25, 30], [35, 40, 45]])

arr_2d[1,1] #it will have the same result as the previous.

25

In [56]:
import numpy as np

arr_2d = np.array([[ 5, 10, 15],[ 20, 25, 30], [35, 40, 45]])

arr_2d[:2,1:] #in this example a slice is used to grab values '10','15' and
#'25' and '30'.

#in an output that displays the following:

#        0    1    2
#array([[ 5, 10, 15],  0
#       [20, 25, 30],  1
#       [35, 40, 45]]) 2

#how this works is that '[:2', means that we will capture all real numbers
#before index '2'. in this case, list:

#[35, 40, 45] <--- is left out
#[ 5, 10, 15] and [20, 25, 30] <--- is referred to

#then, the next ',1:]' means that we will capture all real numbers
#after index '1'. in this case, placements:

#[10,15] amd [25,30] <--- is referred to


array([[10, 15],
       [25, 30]])

In [68]:
import numpy as np

arr[0:11]

boolean_arr = arr < 5

boolean_arr

arr[boolean_arr]

array([0, 1, 2, 3, 4])

In [70]:
#YOU CAN DO ONE LINE OF CODE LIKE THE ONE BELOW------------->

In [72]:
import numpy as np

arr[0:11]

arr[arr<5]

array([0, 1, 2, 3, 4])

In [2]:
#NEXT LESSONS---------------------------------------------------------------->

In [ ]:
np.sqrt(arr)